# Group Members:
#  Suresh Ande  (G01381683)
#  Chandrashakar Gudipally (G01410349)
#  Abhishek Darana ( G01408181) 
#  Anjan kumar sripati panditaradhyula (G01407403)
#  demo



FROM tomcat:9.0-jdk15
COPY SWE645AS2.war /usr/local/tomcat/webapps/