// Group Members:
//  Suresh Ande  (G01381683)
//  Chandrashakar Gudipally (G01410349)
//  Abhishek Darana ( G01408181) 
//  Anjan kumar sripati panditaradhyula (G01407403)

// demo


pipeline {
    agent any
    environment {
        DOCKERHUB_PASS = credentials('dockerhubcred')
        DOCKER_TAG = "latest"
        def dateTag = new Date().format("yyyyMMdd-HHmmss")
    }
    stages {
        stage("Building the Student Survey Image") {
            steps {
                
                script {
                    checkout scm                     
                    
                    sh 'pwd'
                    sh 'ls -al SWE645AS2/WebContent/'
                    sh 'rm -rf *.war'
                    sh 'jar -cvf SWE645AS2/SWE645AS2.war -C SWE645AS2/WebContent .'  
                    sh 'echo ${BUILD_TIMESTAMP}'
                    
                    withCredentials([usernamePassword(credentialsId: 'dockerhubcred', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
                                 sh "echo \$DOCKERHUB_PASS | docker login --username \$DOCKERHUB_USER --password-stdin"
                                 def customImage = docker.build("suresh999/studentsurvey645:${dateTag}", "./SWE645AS2")
                                 
                    }  
                }
            }
        }
        stage("Pushing Image to DockerHub") {
            steps {
                script {
                    sh "docker push suresh999/studentsurvey645:${dateTag}"
                }
            }
        }
        stage("Deploying to Rancher as single pod") {
            steps {                                  
                  sh 'kubectl set image deployment/studentsurvey-pipeline container-0=suresh999/studentsurvey645:${dateTag} -n default'         
            }
        }
        stage("Deploying to Rancher with load balancer") {
            steps { 
                sh 'kubectl set image deployment/studentsurvey-lb container-0=suresh999/studentsurvey645:${dateTag} -n default'
            }
        }
    }
}
